### ISSUE TITLE
wordreference doesn't show me any button

### ISSUE THREAD

**Issue by omega3** [OoDeLally/anki-add-hooks-userscripts#24]
I followed instructions and installed google-translate and wordreference.

google-translate shows
https://i.imgur.com/jPE2CWt.png

Wordreference doesn't show me any button:
https://i.imgur.com/6QqqxS1.png

How can I provide you with debug info?

**Comment by OoDeLally** [comment]
Hello,
Thank you for your feedback.
I think I fixed it now. Can you reinstall the script and try again?
9af6598847f71bfc50bd3dd816f21132f190b128
