### ISSUE TITLE
Reverso Context

### ISSUE THREAD

**Issue by Jackabs3** [OoDeLally/anki-add-hooks-userscripts#28]
Hello! Thank you so much for a great concept!!!! The button doesn't show up for reverso.net (Im using chrome and tampermonkey). However, I was wondering if there is any way possible to add this for the context.reverso.net site? I am creating sentences from verbs (The Big Silver Book of Russian Verbs) by looking up the verb conjugation on reverso and finding a sentence for each (ie i eat, you eat, i ate, etc). It is taking me forever to get sentences for many of the conjugations by copying and pasting (especially with the other verb books for other languages that I still have to do). To have a single button that automatically adds the english sentence on front and russian sentences on back (or the other languages I also am learning - German, French, Italian) would be absolutely PHENOMENAL!!!!! Is there any way to do this? Thank you so much for your time.

**Comment by OoDeLally** [comment]
I added the feature for contextual subdomain. ac74ff431481fba703275d1a543bac5c66a21464.
Should work for your purpose.
