### ISSUE TITLE
Support for right to left languages in reverso context

### ISSUE THREAD

**Issue by Pierre33400** [OoDeLally/anki-add-hooks-userscripts#33]
Can the script for reverso context be modified as follows, because with .src.ltr or .trg.ltr in the selector, it doesn't work for rtl languages such as arabic? Thanks.

```
const extractFrontText$4 = containerDiv =>
    stringifyNodeWithStyle(querySelector(containerDiv, '.src > .text'));

  const extractBackText$4 = containerDiv =>
    stringifyNodeWithStyle(querySelector(containerDiv, '.trg > .text'));
```

I tried and it works.

**Comment by OoDeLally** [comment]
Thank you Pierre. Fixed in https://github.com/OoDeLally/anki-add-hooks-userscripts/commit/f3e366f82fad39d48f5ca2b8230315c55ca0d1b7
