### ISSUE TITLE
WRD table was not found and #noEntryFound was not found.

### ISSUE THREAD

**Issue by ddavout** [OoDeLally/anki-add-hooks-userscripts#34]
>> Amazon Pulisher Services activated. Russian:523:13
Échec du chargement pour l’élément <script> dont la source est « https://c.amazon-adsystem.com/aax2/apstag.js ». Russian:1:1
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://as-sec.casalemedia.com/cygnus?s=311556&v=7.2&r=%7B%2…C%22ext%22%3A%7B%22source%22%3A%22prebid%22%7D%7D&ac=j&sd=1&. Raison : échec de la requête CORS.

DEBUG - (CMP) Using configuration: 
Object { update: update()
, customPurposeListLocation: "./purposes.json", globalVendorListLocation: "/.well-known/cmp_pubvendors.json", globalConsentLocation: "./portal.html", storeConsentGlobally: false, storePublisherData: false, logging: "debug", localization: {…}, forceLocale: null, gdprApplies: true, … }
cmp.complete.bundle.js:1:17790
DEBUG - (CMP) Read consent data from local cookie <empty string> cmp.complete.bundle.js:1:17790
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://ib.adnxs.com/ut/v3/prebid. Raison : échec de la requête CORS.

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://ap.lijit.com/rtb/bid?src=prebid_prebid_3.1.0. Raison : échec de la requête CORS.

on: %100 bundle.min.js:5:1494
off: %50 bundle.min.js:5:1588
off: %25 bundle.min.js:5:1588
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://wordreference-d.openx.net/w/1.0/arj?ju=https%3A%2F%2…ttop%2Cadrightbottom&auid=540405437%2C540405435%2C540405436&. Raison : échec de la requête CORS.

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://fastlane.rubiconproject.com/a/api/fastlane.json?acco…68&rp_floor=0.01&rp_secure=1&slots=1&rand=0.5588865870416092. Raison : échec de la requête CORS.

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://fastlane.rubiconproject.com/a/api/fastlane.json?acco…8&rp_floor=0.01&rp_secure=1&slots=1&rand=0.11387545795204235. Raison : échec de la requête CORS.

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://fastlane.rubiconproject.com/a/api/fastlane.json?acco…8&rp_floor=0.01&rp_secure=1&slots=1&rand=0.06409908051190782. Raison : échec de la requête CORS.

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://ssc.33across.com/api/v1/hb. Raison : échec de la requête CORS.
3
La demande d’accès aux cookies ou au stockage sur « <URL> » a été bloquée car elle provenait d’un traqueur et que le blocage de contenu est activé. 5
DEBUG - (CMP) Successfully loaded CMP version: 0.0.0 in 222ms cmp.complete.bundle.js:1:17790
INFO - (CMP) Notify event: isLoaded cmp.complete.bundle.js:1:17790
:> GDPR: GDPR-noCookie-true -> GA Russian:1673:83
** WOTD received successfully. OK Russian:1430:41
INFO - (CMP) Notify event: cmpReady cmp.complete.bundle.js:1:17790
AnkiAddHooks: Error during web page scraping. 
    Please report the following infos at:
    https://github.com/OoDeLally/anki-add-hooks-userscripts/issues

     Message: .WRD table was not found and #noEntryFound was not found.

     Page: https://www.wordreference.com/enru/Russian.

     Hook Template Version: 2.2.0.

     Hook Userscript Name: wordreference.com.

     Hook UserScript Version: 2.4.
    Anki Add Hooks for WordReference.com.user.js:511:13
>> Ads Failsafe timeout Russian:797:61
INFO - (CMP) Proccess command: getVendorList, parameter: null cmp.complete.bundle.js:1:17790
INFO - (CMP) Queuing command: getVendorConsents until consent data is available cmp.complete.bundle.js:1:17790
DEBUG - (CMP) No consent data found. Showing consent tool cmp.complete.bundle.js:1:17790
INFO - (CMP) Proccess command: showConsentTool, parameter: undefined cmp.complete.bundle.js:1:17790
>> No slots were requested. Russian:759:25
>> Slots-Requested: SReq-No -> GA Russian:763:33
>> DFP success Russian:687:25
>> DFP-loading: DFP-Success -> GA Russian:691:33

​
Thanks

**Comment by OoDeLally** [comment]
Hey @ddavout, thanks for reporting this issue.
It should be fixed now. 
Update here https://github.com/OoDeLally/tampermonkey-anki-add-hooks/raw/master/hooks/wordreference_com_hook.user.js

Re-open the issue if the issue persists.

https://github.com/OoDeLally/anki-add-hooks-userscripts/commit/c6c6b4ddd1dfb5b6159b5005abfa1e09d6cb1c80

**Comment by ddavout** [comment]
Thanks to *you* !

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
