### ISSUE TITLE
WordReference Button not appearing

### ISSUE THREAD

**Issue by samerlinger** [OoDeLally/anki-add-hooks-userscripts#37]
OS: macOS 10.15.4
Browser Chrome 81.0.4044.138
Extension Tampermonkey 4.9
Version of the Tampermonkey/Greasemonkey script 2.5

Wordreference does not show buttons to add for Spanish-English or English-Spanish. Notable the URL for these two is now in the format:
- https://www.wordreference.com/es/translation.asp?tranword=food
- https://www.wordreference.com/es/en/translation.asp?spen=comida

Rather than the format used for seemingly all other translations (eg www.wordreference.com/fren/oui)

I have not been able to figure this issue out on my own

**Comment by OoDeLally** [comment]
Thanks for the report. WordReference indeed has very peculiar urls, and they can only be fixed empirically.
This should be solved now.
https://github.com/OoDeLally/anki-add-hooks-userscripts/commit/3dfb4f7cdeb9af0ae6e127d08e8da34bee8ee4a0
Happy learning!

**Comment by OoDeLally** [comment]
Closing the issue. Re-open it the problem persists.
