### ISSUE TITLE
Template issue

### ISSUE THREAD

**Issue by bibizombie** [OoDeLally/anki-add-hooks-userscripts#40]
**Your software**
 - OS: MacOsCatalina 10.15.7
 - Anki for Mac Destkop Version 2.1.35 (84dcaa86)
 - Browser: Chrome Version 87.0.4280.88 (Official Build) (x86_64)
 - Extension: Tampermoney Version 4.11
 - Script: Anki Add Hooks for WordReference.com Version 2.6

**Describe the bug**
Hello and thank you for your script. I just installed it and am having the following issue:
I think that the size of the text in the flashcards should be growing from large to small.
You can see on the below screenshot that the most important words (at the top) are actually smaller, and the example sentence in grey is the largest. 
How can I change this?
(Sorry I am not familiar with coding and Github).

**Screenshot**
![image](https://user-images.githubusercontent.com/75684717/101502482-61ba6980-3947-11eb-824c-a0522f887971.png)

**Comment by OoDeLally** [comment]
Hi @bibizombie,
Thanks for the report.
This should fix it.
https://github.com/OoDeLally/anki-add-hooks-userscripts/commit/070055cfaa2e9473f922c3d45fa17da7d449bdc8

**Comment by bibizombie** [comment]
Hi @OoDeLally,
Many thanks for fixing this! 
It seems to work well on my side.
Cheers!

**Comment by bibizombie** [comment]
Hi @OoDeLally,
How do you change the deck and the card type association, once it has been set (through Chrome)?
I can't find a way to modify that.
Thanks in advance!

**Comment by OoDeLally** [comment]
Hi @bibizombie 
I didn't implemented that feature (laziness?)
However you can modify the storage by following these steps: https://stackoverflow.com/a/56918709/1541141

You should see something like this 
```json
{
    "deckName_en -> cz": "čeština",
    "deckName_en -> fr": "Default",
    "deckName_fr -> en": "enfr",
    "modelName_en -> cz": "Basic (and reversed card)",
    "modelName_en -> fr": "Basic",
    "modelName_fr -> en": "Basic (and reversed card)"
}
```

Either delete the keys or modify the value directly.

**Comment by bibizombie** [comment]
Great, thank you @OoDeLally
