### ISSUE TITLE
Support of pons.com would be great!

### ISSUE THREAD

**Issue by ajyta** [OoDeLally/anki-add-hooks-userscripts#45]
Hello Pascal,
thank you for the great script. Unfortunately reverso.net does not support suggestions within the search field, it is a little bit uncomfortable if you have longer lists. I've tried to write my own userscript, but as an firmware developer I'm a little bit lost ;-). Is there already an implementation of other dictionary providers which could be made public?

BR,
Peter

**Comment by OoDeLally** [comment]
Hi @ajyta, I'm not sure I understand what you're trying to do with Pons.com that you cannot do with reverso.

As far as I know there isn't any script made for pons.com yet.

You're welcome to give it a try! I agree creating a new script is not the most user-friendly experience, I created this project a long time ago. I can always help you getting started if you have some specific questions or problem.

**Comment by ajyta** [comment]
Hi Pasca,
thanks for the fast response. I gave it a try, but to create such a script is a little bit to hard for me ;-).
The difference between pons and reverso is, that pons proposes after typing in some letters the words which may be suitable. That is especially good if you don't know how the word is exactly written. Within reverso you have to type the whole word correctly, till you see the translation.

But I understand now, that may be a lot of effort writing a script for another provider and it's not just changing some URLs and some HTML Tags...

Thank you,
Peter

**Comment by OoDeLally** [comment]
@ajyta Try https://www.wordreference.com/, they do have an autocomplete feature in the search box.

**Comment by ajyta** [comment]
Thanks, wordreference would be the best engine and also supports a little fuzzysearch, but unfortunately exactly my combination Italian-German is not available there. So bad :-(( 

But many thanks for your excellent support! Maybe I have to get a little bit more into this Tampermonkey hook story. 

I have modified your script anyway a little bit to strip of all the HTML stuff around the field1 & field2 for better sorting and also to make it not so strict accepting only Card type with exactly two fields (so I can have 2+), but this was just botched without knowing the overall structure behind your code.

Many thanks,
Peter
