### ISSUE TITLE
Reverso not working anymore

### ISSUE THREAD

**Issue by bliscosque** [OoDeLally/anki-add-hooks-userscripts#47]
- OS: Windows 11
 - Browser Tried on Opera and Edge
 - Extension Tampermonkey 4.14.6152

**Describe the bug**
Since around 2 weeks, reverso.net stop appearing the "add" button. 

**To Reproduce**
1) As an example, I go to the following page:
https://context.reverso.net/übersetzung/deutsch-portugiesisch/schaffung
2) I can see that tampomonkey is enabled and have full access 
![image](https://user-images.githubusercontent.com/59454927/153741828-6814d141-18a7-4899-a3a7-2c3aacc47479.png)
3) In the page, I cannot see the add button:
![image](https://user-images.githubusercontent.com/59454927/153741856-2a8cc058-8d84-4af3-a8ae-6552ffd2ef5e.png)

Kindly ask your help. I really enjoy and use a lot your add-on!!! And thanks a lot for making it and turning it available.

BR

**Comment by OoDeLally** [comment]
Hello @bliscosque, yes there was a problem with the url matching. I updated it, it should work now.

**Comment by bliscosque** [comment]
Hi @OoDeLally , thanks a lot on your help!
Still, I believe it's working only in latest table (translation). I cannot see the add button for the sample translations. I'm, attaching a screenshot.
![image](https://user-images.githubusercontent.com/59454927/154288849-0b4fe0c0-9672-4f32-b15e-e45101c1e897.png)

**Comment by OoDeLally** [comment]
hmm they have so many formats... :cry: 
Should work now :wink:

**Comment by bliscosque** [comment]
Yes man, and I saw they've change their layout recently (probably that's why it stopped working).
I updated the script and now it's working fine!
Thanks REALLY much!
