### ISSUE TITLE
Cannot Switch Card Model

### ISSUE THREAD

**Issue by batikhaxa** [OoDeLally/anki-add-hooks-userscripts#52]
**Your software**
 - OS: [e.g. Windows 10, iOS8.1]
 - Browser [e.g. Chrome, Firefox, Safari] & Version [e.g. 22]
 - Extension [e.g. Tampermoney, Greasemonkey] & Version [e.g. 1.4.8]
 - Version of the Tampermonkey/Greasemonkey script (Click on icon > Dashboard > Column "Version" of the installed script.)

**Describe the bug**
I started using this userscript for the first time today with WordReference. When clicking the Add button, the prompt to pick a deck and then a model shows up correctly. However, when picking a model, I initially picked a multi-field (more than two) card model, resulting in an error.

Now when I try to click Add again, I always get this error, without a prompt to pick a new Card Model, hence making it impossible for me to use the script as intended:
![image](https://github.com/OoDeLally/anki-add-hooks-userscripts/assets/137380050/556ec156-f76c-47c5-bea3-7a1b9df8780c)

I've tried reinstalling the script via TamperMonkey, deleting cookies/cache and looking through the code to see if I can redefine it manually but no luck so far. 

**To Reproduce**
1. Using a fresh install of the script, go to WordReference
2. Pick a deck
3. Pick a card model with more than 2 fields

**Comment by OoDeLally** [comment]
Yeah the tampermonkey storage is not easy to access, you can find how there https://stackoverflow.com/questions/56918239/where-is-tampermonkeys-storage-tab-to-edit-the-storage-content

**Comment by batikhaxa** [comment]
Thank you! ☀
